In [8]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression  # Changed to LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix




In [9]:
d_tr = pd.read_csv(r'C:\Users\15205\Desktop\ECE562-experiment\last data set2\train_dataset.csv')

In [10]:
#d_tr= df.drop(columns=['id','proto', 'service','state'], axis=1)

In [11]:
d_tr['Hit/Miss'].unique()

array([0, 1], dtype=int64)

In [12]:
d_tr['Hit/Miss'].unique()

array([0, 1], dtype=int64)

In [13]:
#d_tr['Hit/Miss'].replace({'READ': 0, 'WRITE': 1}, inplace=True)

In [14]:
d_tr['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)

C:\Users\15205\AppData\Local\Temp\ipykernel_50536\1753296085.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d_tr['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)
C:\Users\15205\AppData\Local\Temp\ipykernel_50536\1753296085.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  d_tr['A

In [15]:
d_tr.head()

Memory Address  Cache Set  Access Type  Cycle Count  Data Size  Hit/Miss
0         1048576          0            0            7         64         0
1         1052672         64            0           11         64         0
2         1056768        128            0           16         64         0
3         1060880        192            0           21         64         0
4         1064968        256            0           26         64         0

In [17]:
df_test = pd.read_csv(r'C:\Users\15205\Desktop\ECE562-experiment\last data set2\test_dataset.csv')

In [78]:
#df_test['Hit/Miss'].replace({'READ': 0, 'WRITE': 1}, inplace=True)


In [18]:
df_test['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)

C:\Users\15205\AppData\Local\Temp\ipykernel_50536\3896847342.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)
C:\Users\15205\AppData\Local\Temp\ipykernel_50536\3896847342.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_t

In [19]:
#df_test= df_test.drop(columns=['id','proto', 'service','state'], axis=1)


In [20]:
scaler = StandardScaler()


In [21]:
X_train = d_tr.drop(['Hit/Miss'], axis=1)
y_train = d_tr['Hit/Miss']


In [22]:
df_test.head()

Memory Address  Cache Set  Access Type  Cycle Count  Data Size  Hit/Miss
0         1048576          0            0            7         64         0
1         1052672         64            0           11         64         0
2         1056768        128            0           16         64         0
3         1060880        192            0           21         64         0
4         1065480        264            0           26         64         0

In [23]:

X_test = df_test.drop(['Hit/Miss'], axis=1)
y_test = df_test['Hit/Miss']


In [24]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [25]:
model = LogisticRegression()

In [26]:
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [27]:
y_pred = model.predict(X_test_scaled)

In [28]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [29]:
print(f"Accuracy: {accuracy * 100:.4f}%")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Accuracy: 69.5113%
Confusion Matrix:
[[46297    76]
 [35404 34594]]
Precision: 0.9978
Recall: 0.4942
