In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression  # Changed to LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix




In [2]:
d_tr = pd.read_csv(r'C:\Users\15205\Desktop\ECE562-experiment\train_data.csv')

In [3]:
#d_tr= df.drop(columns=['id','proto', 'service','state'], axis=1)

In [4]:
d_tr['Access Type'].unique()

array([0, 1], dtype=int64)

In [5]:
d_tr['Access Type'].unique()

array([0, 1], dtype=int64)

In [6]:
d_tr['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)

C:\Users\15205\AppData\Local\Temp\ipykernel_23724\1753296085.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d_tr['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)


In [7]:
df_test = pd.read_csv(r'C:\Users\15205\Desktop\ECE562-experiment\test_data.csv')

In [8]:
df_test['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)


C:\Users\15205\AppData\Local\Temp\ipykernel_23724\4107855166.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Access Type'].replace({'READ': 0, 'WRITE': 1}, inplace=True)


In [9]:
#df_test= df_test.drop(columns=['id','proto', 'service','state'], axis=1)


In [10]:
scaler = StandardScaler()


In [11]:
X_train = d_tr.drop(['Access Type'], axis=1)
y_train = d_tr['Access Type']


In [12]:
df_test.head()

PC  Memory Address  Cache Set  Cycle Count  Time Since Last Access  \
0  4311510         9283968       1702     58387257                 1987728   
1  4311510         9797828       1539     69464897                 1765362   
2  4277926         1396248       1336     67926610                 3139398   
3  4311551         9441248         63     58547360                 2111943   
4  4209619         3305792        453     50066839                 2501294   

   Valid Status  Dirty Status  Cache Occupancy  Last Eviction Cycle  Hit/Miss  \
0             1             0               16                    0         0   
1             1             0               16                    0         0   
2             1             0               16                    0         0   
3             1             0               16                    0         0   
4             1             0               16                    0         0   

   Access Type  
0            0  
1            0  
2            0  
3            0  
4            0

In [13]:

X_test = df_test.drop(['Access Type'], axis=1)
y_test = df_test['Access Type']


In [14]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [17]:
y_pred = model.predict(X_test_scaled)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [18]:
print(f"Accuracy: {accuracy * 100:.4f}%")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Accuracy: 99.7201%
Confusion Matrix:
[[197118    362]
 [   225  12010]]
Precision: 0.9707
Recall: 0.9816
